// Off-turn armory research — one-time resource unlocks (mirrors concurrentPlay backend).
// Prototype modules become available in the Refit Yard; decrees apply their bonus immediately.
//
// MIRROR. `ARMORY_ITEMS` and `RELIC_PROJECTS` below are deep-equal copies of the canonical
// tables in `base44/shared/catalog.ts`; `test/catalog-mirror.test.js` proves it field for
// field. Change the catalog first, then copy the literal across — never the other way round,
// and never add a UI-only field to a mirrored row (this catalog has no allowlist).
// `ARMORY_KINDS` is display metadata and is deliberately frontend-only.
export const ARMORY_ITEMS = {
  // ── Fortress modules — certified in the Armory, fitted in the bays ──
  citadel_plate: { key: "citadel_plate", label: "Citadel Plate", kind: "module", tier: "I", cost: { steel: 6, manpower: 2 }, effects: [{ scope: "macro", key: "capitalDefense", value: 6 }], desc: "Certify +6 defense prototype armor for the Refit Yard" },
  juggernaut_reactors: { key: "juggernaut_reactors", label: "Juggernaut Reactors", kind: "module", tier: "I", cost: { steel: 5, fuel: 4 }, effects: [{ scope: "economy", key: "income.fuel", value: 1 }], desc: "Certify an all-terrain prototype engine that marches on 1 Fuel instead of 2" },
  munitions_works: { key: "munitions_works", label: "Munitions Works", kind: "module", tier: "I", cost: { steel: 6, fuel: 3 }, effects: [{ scope: "economy", key: "income.steel", value: 1 }, { scope: "economy", key: "income.fuel", value: 1 }, { scope: "economy", key: "income.manpower", value: 1 }], desc: "Certify a prototype industry deck yielding +1 of every resource" },
  field_assay: { key: "field_assay", label: "Field Assay Office", kind: "module", tier: "I", cost: { steel: 4, manpower: 3 }, effects: [{ scope: "economy", key: "fragmentYield", value: 1 }], desc: "A bench, a scale and a licensed assayer at the pit head. Finds are classed where they are lifted, and the keel stops carrying spoil home to learn it was spoil." },
  cipher_hall: { key: "cipher_hall", label: "Cipher Hall", kind: "module", tier: "I", cost: { steel: 6, manpower: 4 }, effects: [{ scope: "economy", key: "fragmentYield", value: 1 }, { scope: "economy", key: "buildTurns", value: -1 }], desc: "Two sealed housings, a reading room and a standing guard. Objects held here are studied rather than stored, and the works that need them no longer wait on a courier." },
  muster_decks: { key: "muster_decks", label: "Muster Decks", kind: "module", tier: "I", cost: { steel: 5, manpower: 4 }, effects: [{ scope: "macro", key: "armyCap", value: 10 }], desc: "Barracks, drill floor and a ramp wide enough for a company in column. Recruits are raised at the keel and walk aboard, instead of marching a fortnight to reach it." },
  sortie_gates: { key: "sortie_gates", label: "Sortie Gates", kind: "module", tier: "I", cost: { steel: 5, manpower: 2 }, effects: [{ scope: "tactical", key: "initiative", value: 2 }], desc: "Four ports cut low in the skirt armor, each with its own ramp and klaxon. A keel that can be ringed can still be the one that opens the fighting." },
  granary_decks: { key: "granary_decks", label: "Granary Decks", kind: "module", tier: "I", cost: { steel: 4, manpower: 5 }, effects: [{ scope: "macro", key: "supplyRange", value: 1 }, { scope: "tactical", key: "moraleTest", value: 1 }], desc: "Sealed bins, salt cellars and a quartermaster who answers to the Ministry alone. A ringed keel is starved out or it is not taken, and these decks decide which." },
  assembly_hall: { key: "assembly_hall", label: "Assembly Hall", kind: "module", tier: "I", cost: { steel: 5, manpower: 5 }, effects: [{ scope: "tactical", key: "moraleTest", value: 1 }, { scope: "macro", key: "armyCap", value: 5 }], desc: "A floor, a rail and benches for the parish delegates. A house that lets its people be heard at the Sessions finds the levy answers faster when it is called." },
  pilgrim_berths: { key: "pilgrim_berths", label: "Pilgrim Berths", kind: "module", tier: "I", cost: { steel: 3, manpower: 6 }, effects: [{ scope: "economy", key: "income.manpower", value: 1 }], desc: "Bunks for the walkers who follow every keel to the Anchor Fields. They are fed, counted and put to work, and a few of them stay on the muster roll." },
  ministry_mast: { key: "ministry_mast", label: "Ministry Mast", kind: "module", tier: "I", cost: { steel: 4, fuel: 2 }, effects: [{ scope: "macro", key: "losRange", value: 1 }], desc: "A lattice mast, a heliograph and a wire office that never closes. Field Orders reach the columns off-turn, and the herald's word travels one full day further than it did." },
  launch_rails: { key: "launch_rails", label: "Launch Rails", kind: "module", tier: "II:Eng", cost: { steel: 7, fuel: 5, fragments: { engine: 3 } }, effects: [{ scope: "macro", key: "unit.fighter.attack", value: 1 }, { scope: "macro", key: "unit.fighter.speed", value: 1 }], desc: "Precursor rail stock, cut down and bolted to the upper deck. The air wing rebases to the keel between sorties and comes off the rails already at speed." },
  march_klaxons: { key: "march_klaxons", label: "March Klaxons", kind: "module", tier: "II:Ciph", cost: { steel: 6, fuel: 3, fragments: { cipher: 3 } }, effects: [{ scope: "macro", key: "unit.riflemen.speed", value: 1 }, { scope: "macro", key: "unit.crawler.speed", value: 1 }], desc: "Cipher-cut horns on the upper works, sounding a cadence nobody taught us. Columns inside the keel's shadow step to it without being ordered to, and the day's ground comes cheaper." },
  sloped_casemates: { key: "sloped_casemates", label: "Sloped Casemates", kind: "module", tier: "II:Cache", cost: { steel: 9, manpower: 3, fragments: { cache: 3 } }, effects: [{ scope: "macro", key: "capitalDefense", value: 3 }, { scope: "tactical", key: "unit.riflemen.defense", value: 1 }], desc: "Cache alloy rolled thin and hung at an angle no shell likes. Boarding parties lose a deck to the geometry before a single storm party has fired." },
  pattern_shop: { key: "pattern_shop", label: "Pattern Shop", kind: "module", tier: "II:Cache", cost: { steel: 8, fuel: 4, fragments: { cache: 2 } }, effects: [{ scope: "economy", key: "buildTurns", value: -1 }, { scope: "economy", key: "fragmentYield", value: 1 }], desc: "Jigs, gauges and a shelf of analyzed patterns. Certification stops being an argument between two foundries and becomes a drawing, and the works come off the floor a watch early." },
  // ── Ideology decrees — the axis moves the moment the seal dries ──
  war_bonds_decree: { key: "war_bonds_decree", label: "Decree of War Bonds", kind: "decree", tier: "I", axis: "economy", direction: 1, cost: { manpower: 3, fuel: 2 }, effects: [{ scope: "economy", key: "income.steel", value: 1 }], desc: "+1 Steel income — the treasury issues war scrip" },
  fuel_ration_act: { key: "fuel_ration_act", label: "Fuel Rationing Act", kind: "decree", tier: "I", axis: "economy", direction: -1, cost: { steel: 4, manpower: 2 }, effects: [{ scope: "economy", key: "income.fuel", value: 1 }], desc: "+1 Fuel income — civilian stocks are seized for the front" },
  universal_levy: { key: "universal_levy", label: "Decree of the Universal Levy", kind: "decree", tier: "I", axis: "mobilization", direction: -1, cost: { steel: 3, manpower: 3 }, effects: [{ scope: "macro", key: "armyCap", value: 15 }], desc: "+15 army cap — every citizen owes service" },
  hearth_and_bulwark: { key: "hearth_and_bulwark", label: "Hearth & Bulwark Edict", kind: "decree", tier: "I", axis: "authority", direction: -1, cost: { steel: 5, manpower: 2 }, effects: [{ scope: "macro", key: "capitalDefense", value: 1 }, { scope: "macro", key: "unit.riflemen.defense", value: 1 }], desc: "+1 capital defense and +1 riflemen defense — the home front digs in" },
  emergency_powers_act: { key: "emergency_powers_act", label: "The Emergency Powers Act", kind: "decree", tier: "I", axis: "authority", direction: 1, cost: { steel: 4, manpower: 3 }, effects: [{ scope: "tactical", key: "initiative", value: 1 }, { scope: "tactical", key: "moraleTest", value: -1 }], desc: "The Assembly hands the Marshal absolute command for the duration and adjourns. Orders arrive a day sooner and are obeyed without argument; nothing said afterward will rally a broken line." },
  sealed_sites_order: { key: "sealed_sites_order", label: "The Sealed-Sites Order", kind: "decree", tier: "I", axis: "authority", direction: 1, creedLock: "flight", cost: { steel: 5, manpower: 4 }, effects: [{ scope: "macro", key: "capitalDefense", value: 1 }, { scope: "tactical", key: "moraleTest", value: 1 }, { scope: "economy", key: "fragmentYield", value: -1 }], desc: "Chart it, weld it, flag it, march on. The Ministry forbids the opening of any Wake under its flag, and the crews who obey come home whole and carrying less." },
  standing_corps_act: { key: "standing_corps_act", label: "The Standing Corps Act", kind: "decree", tier: "I", axis: "mobilization", direction: 1, cost: { steel: 4, manpower: 6 }, effects: [{ scope: "macro", key: "unit.riflemen.defense", value: 1 }, { scope: "macro", key: "armyCap", value: -10 }], desc: "Service becomes a trade with a wage, a pension and a term of years. The line holds where a levy would have broken, and the muster roll is a great deal shorter." },
  charter_of_passage: { key: "charter_of_passage", label: "The Charter of Passage", kind: "decree", tier: "I", axis: "economy", direction: 1, creedLock: "finished_ledger", cost: { steel: 6, fuel: 3 }, effects: [{ scope: "economy", key: "income.steel", value: 1 }, { scope: "economy", key: "income.fuel", value: 1 }, { scope: "economy", key: "income.manpower", value: -1 }], desc: "Nobody is coming, so passage is bought. Chartered houses carry the Ministry's freight at published rates, take their cut in metal and fuel, and hire away the hands that loaded it." },
  reliquary_act: { key: "reliquary_act", label: "The Reliquary Act", kind: "decree", tier: "I", axis: "creed", direction: 1, cost: { steel: 5, manpower: 4 }, effects: [{ scope: "macro", key: "digSpeed", value: 1 }, { scope: "economy", key: "buildTurns", value: -1 }, { scope: "economy", key: "income.steel", value: -1 }], desc: "A find is consecrated where it lies and worked by licensed crews. The digging goes faster and the works go shorter; the foundries wait, because nothing consecrated goes into a furnace." },
  writ_of_consecration: { key: "writ_of_consecration", label: "The Writ of Consecration", kind: "decree", tier: "I", axis: "creed", direction: 1, creedLock: "recall", cost: { steel: 4, manpower: 5 }, effects: [{ scope: "tactical", key: "moraleTest", value: 1 }, { scope: "economy", key: "fragmentYield", value: 1 }, { scope: "economy", key: "income.steel", value: -1 }], desc: "Every Object is entered on the Recall's roll and held against the day the works answer. Crews dig with a purpose and the yards are told, again, to take less." },
  breaking_yards_act: { key: "breaking_yards_act", label: "The Breaking-Yards Act", kind: "decree", tier: "I", axis: "creed", direction: -1, creedLock: "discarding", cost: { steel: 3, manpower: 5 }, effects: [{ scope: "economy", key: "income.steel", value: 2 }, { scope: "economy", key: "fragmentYield", value: 1 }, { scope: "economy", key: "buildTurns", value: 1 }], desc: "What was left for us we may break. Objects go to the yards whole and leave as metal, alloy and scrap; the works that wanted them whole wait another season." },
  ordinance_common_metal: { key: "ordinance_common_metal", label: "The Ordinance of Common Metal", kind: "decree", tier: "I", axis: "creed", direction: -1, cost: { steel: 4, manpower: 3 }, effects: [{ scope: "economy", key: "income.steel", value: 2 }, { scope: "economy", key: "fragmentYield", value: -1 }], desc: "No find is holy and no seam is spared. Everything lifted is weighed as metal at the foundry gate, and the assayers stop being paid to argue otherwise." },
  wakewatch_act: { key: "wakewatch_act", label: "The Wakewatch Act", kind: "decree", tier: "II:Wake", axis: "economy", direction: 1, cost: { steel: 7, manpower: 4, fragments: { wake: 3 } }, effects: [{ scope: "macro", key: "unit.artillery.attack", value: 1 }, { scope: "tactical", key: "unit.artillery.ranged", value: 1 }], desc: "Chartered crews are licensed to hunt live Wakes and paid by the core. The guns that come back off those hulls outrange anything the foundries have ever drawn." },
  // ── Relic projects — the Armory face of the four Tier-III works ──
  land_dreadnought: { key: "land_dreadnought", label: "The Land-Dreadnought", kind: "relic_project", tier: "III", cost: { steel: 30, fuel: 18, manpower: 12, fragments: { engine: 6, cache: 4 } }, effects: [{ scope: "macro", key: "armyCap", value: 20 }, { scope: "macro", key: "capitalDefense", value: 3 }, { scope: "tactical", key: "unit.crawler.armor", value: 1 }], desc: "A second keel, lesser and meaner: an imperial engine walled in plate until it can take what a fortress takes. The only house that fields two hulls is the house that built one." },
  lance_carriage: { key: "lance_carriage", label: "The Lance Carriage", kind: "relic_project", tier: "III", cost: { steel: 22, fuel: 14, manpower: 8, fragments: { wake: 6, engine: 3 } }, effects: [{ scope: "macro", key: "unit.artillery.attack", value: 3 }, { scope: "tactical", key: "unit.artillery.ranged", value: 2 }, { scope: "macro", key: "capitalDefense", value: -1 }], desc: "A Wake's own gun, cradled on a rail carriage and pointed outward at last. It reaches over fortification instead of through it, and the bay it displaces is never given back." },
  the_beacon: { key: "the_beacon", label: "The Beacon", kind: "relic_project", tier: "III", creedLock: "recall", cost: { steel: 26, fuel: 10, manpower: 20, fragments: { cipher: 8, wake: 4 } }, effects: [{ scope: "macro", key: "losRange", value: 3 }, { scope: "tactical", key: "moraleTest", value: 2 }, { scope: "economy", key: "income.manpower", value: 1 }], desc: "A cipher-cut mast raised to call the Absent home. Every house on the Ground can see the light and count the days; some of them walk toward it and enlist." },
  the_new_ignition: { key: "the_new_ignition", label: "The New Ignition", kind: "relic_project", tier: "III", creedLock: "discarding", cost: { steel: 40, fuel: 24, manpower: 16, fragments: { cache: 8, engine: 6 } }, effects: [{ scope: "economy", key: "income.steel", value: 2 }, { scope: "economy", key: "income.fuel", value: 2 }, { scope: "macro", key: "armyCap", value: -20 }], desc: "A human foundry aimed at the sky — the first hull that is ours. It eats the whole war economy's surplus and every hand the levy can spare, and it asks nobody." },
};

// The four Tier-III works (`docs/TECH_DESIGN.md` §2). A project is a card on the
// map's clock, not a research node: it needs an Object of its class housed in the
// Laboratory, doctrine prerequisites of which at least one is Reclamation, heavy
// conventional resources, classed fragments, and `buildDays` of on-clock
// construction that enemy probes and intercepts can see running. Each has a paired
// `ARMORY_ITEMS` row of kind `relic_project` carrying the identical `cost`.
// `buildDays` is a positive integer count of in-game days and is NOT the `buildTurns`
// effect key, which is a signed modifier where negative means the works finish sooner.
export const RELIC_PROJECTS = {
  land_dreadnought: { key: "land_dreadnought", label: "The Land-Dreadnought", objectClass: "engine", prereq: ["continuous_casting", "pattern_book"], buildDays: 24, cost: { steel: 30, fuel: 18, manpower: 12, fragments: { engine: 6, cache: 4 } }, effects: [{ scope: "macro", key: "armyCap", value: 20 }, { scope: "macro", key: "capitalDefense", value: 3 }, { scope: "tactical", key: "unit.crawler.armor", value: 1 }], desc: "A second keel, lesser and meaner: an imperial engine walled in plate until it can take what a fortress takes. The only house that fields two hulls is the house that built one." },
  lance_carriage: { key: "lance_carriage", label: "The Lance Carriage", objectClass: "wake", prereq: ["saturation_barrage", "assay_procedure"], buildDays: 18, cost: { steel: 22, fuel: 14, manpower: 8, fragments: { wake: 6, engine: 3 } }, effects: [{ scope: "macro", key: "unit.artillery.attack", value: 3 }, { scope: "tactical", key: "unit.artillery.ranged", value: 2 }, { scope: "macro", key: "capitalDefense", value: -1 }], desc: "A Wake's own gun, cradled on a rail carriage and pointed outward at last. It reaches over fortification instead of through it, and the bay it displaces is never given back." },
  the_beacon: { key: "the_beacon", label: "The Beacon", objectClass: "cipher", prereq: ["intercept_bureau", "pattern_book"], buildDays: 40, creedLock: "recall", cost: { steel: 26, fuel: 10, manpower: 20, fragments: { cipher: 8, wake: 4 } }, effects: [{ scope: "macro", key: "losRange", value: 3 }, { scope: "tactical", key: "moraleTest", value: 2 }, { scope: "economy", key: "income.manpower", value: 1 }], desc: "A cipher-cut mast raised to call the Absent home. Every house on the Ground can see the light and count the days; some of them walk toward it and enlist." },
  the_new_ignition: { key: "the_new_ignition", label: "The New Ignition", objectClass: "cache", prereq: ["deep_shaft_works", "continuous_casting"], buildDays: 40, creedLock: "discarding", cost: { steel: 40, fuel: 24, manpower: 16, fragments: { cache: 8, engine: 6 } }, effects: [{ scope: "economy", key: "income.steel", value: 2 }, { scope: "economy", key: "income.fuel", value: 2 }, { scope: "macro", key: "armyCap", value: -20 }], desc: "A human foundry aimed at the sky — the first hull that is ours. It eats the whole war economy's surplus and every hand the levy can spare, and it asks nobody." },
};

export const ARMORY_KINDS = {
  module: { icon: "🛠", label: "Fortress Prototypes", blurb: "Certified designs unlock new modules in the Refit Yard" },
  decree: { icon: "⚖", label: "Ideology Decrees", blurb: "Political edicts — their bonus takes effect the moment they are enacted" },
  relic_project: { icon: "◈", label: "Relic Projects", blurb: "Tier-III works built around a housed Object, on the map's clock and in plain sight" },
};

export const armoryByKind = (kind) => Object.entries(ARMORY_ITEMS).filter(([, i]) => i.kind === kind);

// Classed fragments demanded by a row, `{}` when it asks for none. Tier `I` rows
// never carry them; a `II:*` row carries exactly its own class. Consumers pricing
// an item must add these to the three conventional resources — `cost.fragments` is
// invisible to any affordability check that iterates RESOURCE_KEYS alone.
export const fragmentCost = (item) => (item && item.cost && item.cost.fragments) || {};
