// Delivered art plates — generated sample images keyed to the master image library.
// Regenerating an asset = replacing its URL here; the registry picks it up automatically.
const B = "https://media.base44.com/images/public/6a58196dcd485ecc774cae1b/";

export const PLATE_URLS = {
  // Commanders
  cmdr_butcher: B + "28bda0d61_generated_image.png",
  cmdr_fox: B + "07b164e68_generated_image.png",
  cmdr_bulwark: B + "7cbfc993e_generated_image.png",
  cmdr_firebrand: B + "cbe36cd9b_generated_image.png",
  cmdr_marshal_aggressive: B + "8903886c7_generated_image.png",
  cmdr_marshal_economic: B + "89425865f_generated_image.png",
  cmdr_marshal_defensive: B + "578014a2f_generated_image.png",
  cmdr_field_a: B + "d0e3e9b88_generated_image.png",
  cmdr_field_b: B + "cd8d25f69_generated_image.png",
  cmdr_field_c: B + "2c551ffaa_generated_image.png",
  cmdr_field_d: B + "355b8b821_generated_image.png",
  // Avatars
  avatar_01: B + "baa7dfcc8_generated_image.png",
  avatar_02: B + "f02496dda_generated_image.png",
  avatar_03: B + "47656ca68_generated_image.png",
  avatar_04: B + "956ef3375_generated_image.png",
  avatar_05: B + "9001cb39a_generated_image.png",
  avatar_06: B + "292613bdc_generated_image.png",
  avatar_07: B + "a97d33698_generated_image.png",
  avatar_08: B + "ec692a811_generated_image.png",
  // Faction crests & sigils
  crest_aggressive: B + "126f3c9e8_generated_image.png",
  crest_economic: B + "6c33b6ef7_generated_image.png",
  crest_defensive: B + "54c6561fe_generated_image.png",
  sigil_red: B + "4003db8a4_generated_image.png",
  sigil_blue: B + "5f0fc1c5e_generated_image.png",
  sigil_green: B + "c189910ce_generated_image.png",
  sigil_amber: B + "c5b0d017e_generated_image.png",
  // Units
  unit_riflemen_token: B + "4c4d869df_generated_image.png",
  unit_crawler_token: B + "f1d763874_generated_image.png",
  unit_gunboat_token: B + "1e42bf7fa_generated_image.png",
  unit_fighter_token: B + "7aa521f7d_generated_image.png",
  unit_artillery_token: B + "b74d2a254_generated_image.png",
  unit_riflemen_action: B + "ea89ea34c_generated_image.png",
  unit_crawler_action: B + "8576d546b_generated_image.png",
  unit_gunboat_action: B + "1072f17f8_generated_image.png",
  unit_fighter_action: B + "964509524_generated_image.png",
  unit_artillery_action: B + "fe17bf251_generated_image.png",
  // Fortress-bases & modules
  base_aggressive: B + "ad865dd4b_generated_image.png",
  base_economic: B + "20174f304_generated_image.png",
  base_defensive: B + "b09570b8e_generated_image.png",
  mod_riveted_plating: B + "70ffd67db_generated_image.png",
  mod_bulwark_hull: B + "a618b2052_generated_image.png",
  mod_crawler_drives: B + "ac9f10494_generated_image.png",
  mod_leviathan_turbines: B + "5f10f55f6_generated_image.png",
  mod_salvage_refinery: B + "bf9acecff_generated_image.png",
  mod_arc_smelters: B + "9de9c6a7e_generated_image.png",
  mod_habitat_decks: B + "ef5beaec7_generated_image.png",
  mod_citadel_plate: B + "2ad82ed3f_generated_image.png",
  // Buildings
  bld_barracks: B + "f636ce573_generated_image.png",
  bld_foundry: B + "8c51d6278_generated_image.png",
  bld_refinery: B + "f6166a680_generated_image.png",
  bld_fortifications: B + "5af3ad935_generated_image.png",
  bld_airstrip: B + "5062dce5a_generated_image.png",
  // Terrain
  terr_plains: B + "50079438c_generated_image.png",
  terr_deltas: B + "a3b2474dc_generated_image.png",
  terr_forest: B + "a84ec80a8_generated_image.png",
  terr_hills: B + "abd85817d_generated_image.png",
  terr_highlands: B + "ef00e9c0d_generated_image.png",
  terr_mountains: B + "a295386ec_generated_image.png",
  terr_marsh: B + "26da21ee9_generated_image.png",
  terr_industrial: B + "d8d9006d7_generated_image.png",
  terr_sea: B + "200f575a0_generated_image.png",
  // Weather seals
  wx_clear: B + "89ac1bcc0_generated_image.png",
  wx_rain: B + "39841474e_generated_image.png",
  wx_fog: B + "8a69dd03b_generated_image.png",
  wx_storm: B + "276cd1fe8_generated_image.png",
  wx_snow: B + "4d89eaca1_generated_image.png",
  // Resource tokens
  res_manpower: B + "17eead034_generated_image.png",
  res_steel: B + "8d3b4f307_generated_image.png",
  res_fuel: B + "e21c5a0ed_generated_image.png",
  res_oil_field: B + "70318eed0_generated_image.png",
  // Gap-analysis additions (2026-07) — one example delivered per new category
  decree_war_bonds: B + "c3fd8625a_generated_image.png",
  tech_combined_arms: B + "43cb5e563_generated_image.png",
  design_vanguard: B + "64534ca99_generated_image.png",
  dip_trade_manifest: B + "1bee4aaa5_generated_image.png",
  rank_elite: B + "1f83fbea3_generated_image.png",
  // Medals
  medal_iron_hammer: B + "682569a76_generated_image.png",
  medal_brass_star: B + "084b61e98_generated_image.png",
  medal_defiant_standard: B + "4f37ca8f3_generated_image.png",
  medal_marshals_cross: B + "ffa97c273_generated_image.png",
  // Maneuver cards
  mnv_all_out_attack: B + "c21971486_generated_image.png",
  mnv_attack: B + "fb3c9789d_generated_image.png",
  mnv_defend: B + "9760232f1_generated_image.png",
  mnv_flank: B + "52ae9c1f7_generated_image.png",
  mnv_feint: B + "ecb6945dd_generated_image.png",
  mnv_rally: B + "337682abc_generated_image.png",
  mnv_relentless_pursuit: B + "4a83ced29_generated_image.png",
  // Effect textures
  fx_explosion: B + "10b002581_generated_image.png",
  fx_muzzle: B + "02443bfd4_generated_image.png",
  fx_smoke: B + "73c5dc8ae_generated_image.png",
  fx_sparks: B + "0bc1e4df5_generated_image.png",
  fx_grit: B + "5389b16e2_generated_image.png",
  // Backdrops
  bg_home_hero: B + "379dcf40c_generated_image.png",
  bg_lobby: B + "54e5c77cb_generated_image.png",
  bg_victory: B + "4038dd422_generated_image.png",
  bg_defeat: B + "cf978dae6_generated_image.png",
  bg_commission: B + "21bb0bbb9_generated_image.png",
  bg_parchment_map: B + "8384513be_generated_image.png",
  bg_battle_day: B + "30e669c61_generated_image.png",
  bg_battle_storm: B + "dc88b8060_generated_image.png",
  // Catalogued live hero plates (previously hardcoded in components)
  bg_command_deck: B + "ca29f8b58_generated_image.png",
  bg_hero_banner: B + "3b5791ea2_generated_image.png",
  bg_war_room: B + "0b44e3267_generated_image.png",
  // Ministry marks
  ui_app_crest: B + "f8b0a4645_generated_image.png",
  ui_ministry_seal: B + "16434d5f4_generated_image.png",
  ui_classified_stamp: B + "3462174e8_generated_image.png",
  ui_wax_seal: B + "2fb9b31fe_generated_image.png",
  ui_divider: B + "e68b9c9a3_generated_image.png",
};